
import { Activity } from './types';

export const activities: Activity[] = [
  {
    id: 1,
    name: "Утренняя медитация",
    emoji: "🧘‍♀️",
    startTime: "07:00",
    endTime: "07:30",
    duration: "30 мин",
    color: "bg-emerald-100 border-emerald-300",
    importance: 3,
    completed: false,
    type: "восстановление",
    needEmoji: "🌱",
    date: "2025-06-22"
  },
  {
    id: 2,
    name: "Завтрак",
    emoji: "🥐",
    startTime: "08:00",
    endTime: "08:30",
    duration: "30 мин",
    color: "bg-orange-100 border-orange-300",
    importance: 2,
    completed: true,
    type: "нейтральная",
    date: "2025-06-22"
  },
  {
    id: 3,
    name: "Работа над проектом",
    emoji: "💻",
    startTime: "09:00",
    endTime: "11:00",
    duration: "2 ч",
    color: "bg-blue-100 border-blue-300",
    importance: 3,
    completed: false,
    type: "задача",
    date: "2025-06-22"
  },
  {
    id: 4,
    name: "Прогулка в парке",
    emoji: "🚶‍♀️",
    startTime: "11:30",
    endTime: "12:00",
    duration: "30 мин",
    color: "bg-green-100 border-green-300",
    importance: 2,
    completed: false,
    type: "восстановление",
    needEmoji: "🌳",
    date: "2025-06-22"
  },
  {
    id: 5,
    name: "Обед",
    emoji: "🍽️",
    startTime: "12:30",
    endTime: "13:00",
    duration: "30 мин",
    color: "bg-yellow-100 border-yellow-300",
    importance: 2,
    completed: true,
    type: "нейтральная",
    date: "2025-06-22"
  },
  {
    id: 6,
    name: "Встреча с командой",
    emoji: "👥",
    startTime: "14:00",
    endTime: "15:30",
    duration: "1.5 ч",
    color: "bg-purple-100 border-purple-300",
    importance: 3,
    completed: false,
    type: "смешанная",
    date: "2025-06-22"
  },
  {
    id: 7,
    name: "Спортзал",
    emoji: "🏋️‍♀️",
    startTime: "17:00",
    endTime: "18:30",
    duration: "1.5 ч",
    color: "bg-red-100 border-red-300",
    importance: 3,
    completed: false,
    type: "восстановление",
    needEmoji: "💪",
    date: "2025-06-22"
  },
  {
    id: 8,
    name: "Ужин",
    emoji: "🍝",
    startTime: "19:00",
    endTime: "19:45",
    duration: "45 мин",
    color: "bg-pink-100 border-pink-300",
    importance: 2,
    completed: false,
    type: "нейтральная",
    date: "2025-06-22"
  },
  {
    id: 9,
    name: "Чтение книги",
    emoji: "📚",
    startTime: "21:00",
    endTime: "22:00",
    duration: "1 ч",
    color: "bg-indigo-100 border-indigo-300",
    importance: 2,
    completed: false,
    type: "восстановление",
    needEmoji: "🧠",
    date: "2025-06-22"
  },
  {
    id: 10,
    name: "Подготовка ко сну",
    emoji: "🛏️",
    startTime: "22:30",
    endTime: "23:00",
    duration: "30 мин",
    color: "bg-slate-100 border-slate-300",
    importance: 2,
    completed: false,
    type: "восстановление",
    needEmoji: "😴",
    date: "2025-06-22"
  },
  // Дублируем активности для других дней недели
  {
    id: 11,
    name: "Утренняя зарядка",
    emoji: "🤸‍♀️",
    startTime: "06:30",
    endTime: "07:15",
    duration: "45 мин",
    color: "bg-emerald-100 border-emerald-300",
    importance: 2,
    completed: false,
    type: "восстановление",
    needEmoji: "⚡",
    date: "2025-06-23"
  },
  {
    id: 12,
    name: "Планирование дня",
    emoji: "📋",
    startTime: "08:30",
    endTime: "09:00",
    duration: "30 мин",
    color: "bg-blue-100 border-blue-300",
    importance: 2,
    completed: false,
    type: "задача",
    date: "2025-06-23"
  },
  {
    id: 13,
    name: "Созвон с клиентом",
    emoji: "📞",
    startTime: "10:00",
    endTime: "11:00",
    duration: "1 ч",
    color: "bg-purple-100 border-purple-300",
    importance: 3,
    completed: false,
    type: "смешанная",
    date: "2025-06-23"
  },
  {
    id: 14,
    name: "Йога",
    emoji: "🧘‍♀️",
    startTime: "18:00",
    endTime: "19:00",
    duration: "1 ч",
    color: "bg-green-100 border-green-300",
    importance: 2,
    completed: false,
    type: "восстановление",
    needEmoji: "🕉️",
    date: "2025-06-24"
  }
];
