// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szvousyzsqdpubgfycdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6dm91c3l6c3FkcHViZ2Z5Y2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjQwMTksImV4cCI6MjA2MjQwMDAxOX0.4v7kl7RnYBhHsDPNVH9DvJmUlklbDa_SlbuR2jMCjdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);